version: "3.8"
services:
    app:
        build:
            context: .
            dockerfile: ./dockerfile
        container_name: mafumafu-karaoke-dday
        volumes:
            - /karaoke-dday-db:/usr/src/app/db
        environment:
            X_CT0_TOKEN: ${X_CT0_TOKEN}
            X_AUTH_TOKEN: ${X_AUTH_TOKEN}
            DISCORD_WEBHOOK_URL: ${DISCORD_WEBHOOK_URL}
        networks:
            - mafumafu-karaoke-dday
        restart: unless-stopped
